name: Telegram Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ archiveOnSwipeWithFolders ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Prepare docker
      run: sudo docker build -t telegram-build .

    - name: Telegram Build
      run: sudo docker run --rm -v "$PWD":/home/source telegram-build

    - name: Zip files
      run: cd TMessagesProj/build/outputs/ && sudo zip -r apk.zip apk

    # https://github.com/marketplace/actions/telegram-notify
    - name: Send result
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: TMessagesProj/build/outputs/apk.zip
